
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/proj-courses-f23-7pm-2
owner: ucsb-cs156-f23
repo_name: proj-courses-f23-7pm-2
pull_requests: [{"author":{"id":"U_kgDOBXjycA","is_bot":false,"login":"huangderful","name":""},"headRefName":"rh-load-subjects-auto","number":24,"title":"Rh load subjects auto","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-2/pull/24"}]
