
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/proj-courses-f23-7pm-2
owner: ucsb-cs156-f23
repo_name: proj-courses-f23-7pm-2
pull_requests: [{"author":{"id":"U_kgDOBXjycA","is_bot":false,"login":"huangderful","name":""},"headRefName":"rh-refactor-coursedetails-table","number":42,"title":"Rh Refactored Course Details","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-2/pull/42"},{"author":{"id":"MDQ6VXNlcjcyMjY5NjQz","is_bot":false,"login":"MuMuKow","name":"Andy Ouyang"},"headRefName":"Andy-FixStryker","number":31,"title":"Changed Stryker Enable to Restore","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-2/pull/31"},{"author":{"id":"MDQ6VXNlcjM3Njg1Nzg3","is_bot":false,"login":"tigeryu8900","name":""},"headRefName":"Tiger-FEATURE-MVP-(placeholder)-for-Course-Details-page---F2-Button-to-route-to-placeholder-page","number":29,"title":"Tiger - FEATURE: MVP (placeholder) for Course Details page - F2: Button to route to placeholder page","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-2/pull/29"},{"author":{"id":"U_kgDOBXjycA","is_bot":false,"login":"huangderful","name":""},"headRefName":"rh-load-subjects-auto","number":24,"title":"Rh load subjects auto","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-2/pull/24"}]
