
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/proj-courses-f23-7pm-2
owner: ucsb-cs156-f23
repo_name: proj-courses-f23-7pm-2
pull_requests: [{"author":{"id":"U_kgDOBXmKFg","is_bot":false,"login":"KyleWong288","name":"Kyle Wong"},"headRefName":"Kyle-FixSectionTA","number":38,"title":"Bug fix: Searching for a TA makes the first section appear as a lecture","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-2/pull/38"},{"author":{"id":"U_kgDOBXjycA","is_bot":false,"login":"huangderful","name":""},"headRefName":"rh-reformat-personalSchedulesDetailsPageTest","number":33,"title":"Reformatted the personal schedules details page test to use fixtures instead of being hardcoded","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-2/pull/33"},{"author":{"id":"MDQ6VXNlcjcyMjY5NjQz","is_bot":false,"login":"MuMuKow","name":"Andy Ouyang"},"headRefName":"Andy-FixStryker","number":31,"title":"Changed Stryker Enables to Restores","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-2/pull/31"},{"author":{"id":"MDQ6VXNlcjM3Njg1Nzg3","is_bot":false,"login":"tigeryu8900","name":""},"headRefName":"Tiger-FEATURE-MVP-(placeholder)-for-Course-Details-page---F2-Button-to-route-to-placeholder-page","number":29,"title":"Tiger - FEATURE: MVP (placeholder) for Course Details page - F2: Button to route to placeholder page","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-2/pull/29"},{"author":{"id":"MDQ6VXNlcjM3Njg1Nzg3","is_bot":false,"login":"tigeryu8900","name":""},"headRefName":"Tiger-REFACTOR-replace-logger-with-@Slf4j","number":25,"title":"Tiger - REFACTOR: replace logger with @Slf4j","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-2/pull/25"},{"author":{"id":"U_kgDOBXjycA","is_bot":false,"login":"huangderful","name":""},"headRefName":"rh-load-subjects-auto","number":24,"title":"Rh load subjects auto","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-2/pull/24"},{"author":{"id":"U_kgDOBXjycA","is_bot":false,"login":"huangderful","name":""},"headRefName":"rh-f1-no-story-branch","number":19,"title":"Course Details Page","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-2/pull/19"},{"author":{"id":"U_kgDOBnFWcA","is_bot":false,"login":"raysujf","name":""},"headRefName":"Ray-fixbug","number":17,"title":"Ray - Fix Bug: Creating personal schedule fails first try until quarter field changed","url":"https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-2/pull/17"}]
